version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"  # Привязываем порт 8080 на локальной машине к порту 80 в контейнере
    volumes:
      - .:/var/www/html  # Монтируем текущую директорию в контейнер для мгновенных обновлений
